[package]
name = "cve-2021-4034-rust"
authors = ["Kevin Pham <kevin@deoxy.net>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.23.1"
rand = "0.8.4"

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
codegen-units = 1
